---

## Wait For Servers To Boot

- hosts: "primary,replicas,maxscale"
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: "Waiting For Servers To Initialize"
      wait_for_connection:

## Bootstrap For Ansible

- hosts: "primary,replicas,maxscale"
  become: yes
  become_user: root
  gather_facts: yes
  vars_files:
    - 'inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'
    - 'inventory/group_vars/all.yml'

  pre_tasks:
    - name: "Bootstrapping System For Ansible"
      raw: '{{ pre_task }}'

## Include Sub Playbooks

- name: "Preparing The Servers"
  import_playbook: includes/prepare.yml

- name: "Dev support utils"
  import_playbook: includes/dev_utils.yml

# - name: "Setting Up GFS2"
#   import_playbook: includes/gfs2.yml
#   when: use_s3

- name: "Configuring NVMe and Symlinks"
  import_playbook: includes/configure_nvme.yml
  when: mariadb_has_nvme

- name: "Install ColumnStore from packages"
  import_playbook: includes/install_cs_from_pkgs.yml
  when: mariadb_rpms_path is defined and mariadb_rpms_path != "" and mariadb_rpms_path is not none

- name: "Install ColumnStore from Enterprise repo"
  import_playbook: includes/install_cs_from_enterprise_repo.yml
  when: mariadb_rpms_path is not defined or mariadb_rpms_path == "" or mariadb_rpms_path is none

- name: "Setup Sentry integration for CMAPI"
  import_playbook: includes/sentry.yml

- name: "ColumnStore setup"
  import_playbook: includes/columnstore_setup.yml

- name: "Setting Up ColumnStore Cluster"
  import_playbook: includes/cluster.yml

- name: "Validating Installation"
  import_playbook: includes/validate.yml

- name: "Install MaxScale"
  import_playbook: includes/install_maxscale.yml

- name: "Configuring MaxScale"
  import_playbook: includes/maxscale.yml

- name: "Configuring shared EFS"
  import_playbook: includes/shared_efs.yml
  when: create_shared_efs | bool
