---

- hosts: "all"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Getting MariaDB Enterprise Repo Setup Script"
    get_url:
      url: https://dlm.mariadb.com/enterprise-release-helpers/mariadb_es_repo_setup
      dest: /usr/local/bin/mariadb_es_repo_setup
      mode: 'a+x'

  - name: "Removing Previous MariaDB Yum Repo If Necessary"
    command: rm -rf /etc/yum.repos.d/mariadb*
    when: ansible_os_family == 'RedHat'

  - name: "Removing Previous MariaDB Apt Repo If Necessary"
    command: rm -rf /etc/apt/sources.list.d/mariadb*
    when: ansible_os_family == 'Debian'

  - name: "Setting Up MariaDB Enterprise Repo"
    command: /usr/local/bin/mariadb_es_repo_setup --token={{ enterprise_token }} --skip-tools --mariadb-server-version='{{ mariadb_version }}' --mariadb-maxscale-version='{{ maxscale_version }}' --apply

- hosts: "pm"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Creating CMAPI Folder"
    file:
      path: /opt/cmapi
      state: directory
      mode: '0755'

  - name: "Downloading CMAPI Server"
    unarchive:
      src: https://dlm.mariadb.com/{{ enterprise_token }}/mariadb-enterprise-server/10.5.4-2/cmapi/mariadb-columnstore-cmapi.tar.gz
      dest: /opt/cmapi
      remote_src: yes

  - name: "Installing MariaDB Items"
    package:
      name: '{{ packages }}'
      state: present
      update_cache: yes
    vars:
      packages:
      - '{{ mariadb_server }}'
      - '{{ mariadb_cs_engine }}'
      - '{{ mariadb_backup }}'

  - name: "Configuring Storagemanager"
    template:
      src: ../templates/storagemanager.cnf.j2
      dest: /etc/columnstore/storagemanager.cnf
      owner: mysql
      group: mysql
    when: use_s3 == true

  - name: "Checking If CMAPI Is Already Installed"
    stat:
      path: /etc/systemd/system/mariadb-columnstore-cmapi.service
    register: stat_result

  - name: "Installing CMAPI Server"
    shell:
      cmd: ./service.sh install
      chdir: /opt/cmapi
    when: not stat_result.stat.exists

  - name: "Setting Server IDs"
    replace:
      path: '{{ columnstore_cnf }}'
      regexp: '^#server-id.*1$'
      replace: "server_id = {{ inventory_hostname.split('m')[-1] }}"

  - name: "Remove Bind Address Line (Ubuntu)"
    lineinfile:
      path: '{{ server_cnf }}'
      regexp: '^bind-address'
      state: absent
    when: ansible_distribution == 'Ubuntu'

  - name: "Configuring columnstore.cnf"
    blockinfile:
      path: '{{ columnstore_cnf }}'
      block: |
        character_set_server = utf8
        collation_server = utf8_general_ci
        log_bin = /var/lib/mysql/mariadb-bin
        log_bin_index = /var/lib/mysql/mariadb-bin.index
        relay_log = /var/lib/mysql/mariadb-relay
        relay_log_index = /var/lib/mysql/mariadb-relay.index
        log_slave_updates = ON
        gtid_strict_mode = ON
        log_error = /var/log/mariadb/columnstore/mariadb-error.log
        columnstore_use_import_for_batchinsert=ALWAYS

  - name: "Enabling MariaDB Server"
    systemd:
      name: mariadb
      state: restarted
      enabled: yes

  - name: "Enabling Columnstore Engine"
    systemd:
      name: mariadb-columnstore
      state: restarted
      enabled: yes

  - name: "Enabling CMAPI Server"
    systemd:
      name: mariadb-columnstore-cmapi
      state: restarted
      enabled: yes

- hosts: "mx"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Installing MaxScale Items"
    package:
      name: '{{ packages }}'
      state: present
      update_cache: yes
    vars:
      packages:
      - '{{ maxscale }}'
      - '{{ mariadb_client }}'
