---

- hosts: "all"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:
  - set_fact:
      target_interface: '{{ item }}'
    when: (hostvars[inventory_hostname]['ansible_%s' % item]|default({})).get('ipv4', {}).get('address') == ansible_host or ansible_host in ((hostvars[inventory_hostname]['ansible_%s' % item]|default({})).get('ipv4_secondaries'))|map(attribute='address')|list
    with_items:
      - '{{ ansible_interfaces }}'

  - name: "Setting SELinux Permissive (CentOS)"
    selinux:
      policy: targeted
      state: permissive
    when: ansible_distribution == 'CentOS'

  - name: "Disabling firewalld (CentOS)"
    systemd:
      name: firewalld
      state: stopped
      enabled: False
    when: ansible_distribution == 'CentOS'
    ignore_errors: true

  - name: "Disabling AppArmor (Ubuntu)"
    systemd:
      name: apparmor
      state: stopped
      enabled: no
    when: ansible_distribution == 'Ubuntu'

  - name: "Disabling UFW (Ubuntu)"
    systemd:
      name: ufw
      state: stopped
      enabled: no
    when: ansible_distribution == 'Ubuntu'

  - name: "Upgrading All Packages (CentOS)"
    package:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: "Upgrading All Packages (Ubuntu)"
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: "Rebooting To Apply Updates"
    reboot:

  - name: "Installing Some Prerequisites"
    package:
      name: '{{ packages }}'
      state: present
    vars:
      packages:
      - '{{ git }}'
      - '{{ htop }}'
      - '{{ jemalloc }}'
      - '{{ jq }}'
      - '{{ mlocate }}'
      - '{{ nano }}'
      - '{{ wget }}'

  - name: "Setting System Character Set"
    command: localedef -i en_US -f UTF-8 en_US.UTF-8

  - name: "Adjusting System vm.swappiness"
    sysctl:
      name: vm.swappiness
      value: '10'
      state: present

  - name: "Adjusting System vm.vfs_cache_pressure"
    sysctl:
      name: vm.vfs_cache_pressure
      value: '10'
      state: present

  - name: "Adjusting System txqueuelen"
    lineinfile:
      path: /etc/rc.d/rc.local
      line: '/usr/sbin/ifconfig {{ target_interface }} txqueuelen 10000'
      create: yes

  - name: "Adjusting System net.core.rmem_max"
    sysctl:
      name: net.core.rmem_max
      value: '16777216'
      state: present

  - name: "Adjusting System net.core.wmem_max"
    sysctl:
      name: net.core.wmem_max
      value: '16777216'
      state: present

  - name: "Adjusting System net.ipv4.tcp_rmem"
    sysctl:
      name: net.ipv4.tcp_rmem
      value: '4096 87380 16777216'
      state: present

  - name: "Adjusting System net.ipv4.tcp_wmem"
    sysctl:
      name: net.ipv4.tcp_wmem
      value: '4096 65536 16777216'
      state: present

  - name: "Adjusting System net.ipv4.tcp_no_metrics_save"
    sysctl:
      name: net.ipv4.tcp_no_metrics_save
      value: '1'
      state: present

  - name: "Adjusting System net.core.netdev_max_backlog"
    sysctl:
      name: net.core.netdev_max_backlog
      value: '2500'
      state: present

  - name: "Adding Custom Mappings To /etc/hosts"
    blockinfile:
      path: /etc/hosts
      block: |
        {{ hostvars['pm1'].ansible_host }} pm1
        {{ hostvars['pm2'].ansible_host }} pm2
        {{ hostvars['pm3'].ansible_host }} pm3
        {{ hostvars['mx1'].ansible_host }} mx1

  - name: "Removing Conflicts"
    package:
      name: '{{ mariadb_libs }}'
      state: absent
