- hosts: "primary,replicas,maxscale"
  become: yes
  gather_facts: yes
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml'
    - '../inventory/group_vars/all.yml'

  tasks:
    - name: Determine role label for prompt (primary)
      set_fact:
        role_label: "primary"
      when: "'primary' in group_names"

    - name: Determine role label for prompt (replicas)
      set_fact:
        role_label: "replica{{ groups['replicas'].index(inventory_hostname) + 1 }}"
      when: inventory_hostname in groups['replicas']

    - name: Determine role label for prompt (maxscale)
      set_fact:
        role_label: "maxscale{{ groups['maxscale'].index(inventory_hostname) + 1 }}"
      when: inventory_hostname in groups['maxscale']

    - name: Ensure /etc/bash.bashrc.d directory exists
      file:
        path: /etc/bash.bashrc.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install role-aware prompt for all users (interactive Bash)
      copy:
        dest: /etc/bash.bashrc.d/99-role-prompt.bashrc
        owner: root
        group: root
        mode: '0644'
        content: |
          # Auto-generated by Ansible: role-aware prompt for interactive Bash
          # Only proceed for interactive shells
          case $- in
            *i*) ;;
            *) return ;;
          esac
          # Skip if not bash
          [ -n "$BASH_VERSION" ] || return 0
          case $TERM in
            xterm*|screen*|vt100*|rxvt*) color_term=1 ;;
            *) color_term=0 ;;
          esac
          ROLE_LABEL="{{ role_label | default('host') }}"
          if [ "$color_term" = 1 ]; then
            # Colors: role in bright cyan, user@host in green, path in blue
            PS1='\[\e[96m\]('"$ROLE_LABEL"')\[\e[0m\] \[\e[32m\]\u@\h\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]\\$ '
          else
            PS1='('"$ROLE_LABEL"') \u@\h:\w\\$ '
          fi
          export PS1

    - name: Also show role in MOTD on login
      copy:
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
        content: |
          ======================================================
           MariaDB ColumnStore Deployment
           Host role: {{ role_label | default('host') }}
           System hostname: {{ ansible_hostname }}
          ======================================================
