---

- hosts: "maxscale"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Set Replicas Into Maintenance Mode"
    uri:
      url: http://127.0.0.1:8989/v1/servers/{{ item }}/set?state=maintenance
      method: PUT
      user: admin
      password: mariadb
      status_code: 204
    loop:
       - "mcs3"
       - "mcs2"

- hosts: "mcs1"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Shutting Down ColumnStore Cluster"
    uri:
      url: https://{{ hostvars.mcs1_private.ansible_host }}:8640/cmapi/0.4.0/cluster/shutdown
      method: PUT
      headers:
        Content-Type: application/json
        x-api-key: "{{ api_key }}"
      validate_certs: no
      return_content: yes
      status_code: 200
      body_format: json
      body: '{"timeout":60}'
      timeout: 180

- hosts: "primary,replicas"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Stopping MariaDB Services"
    systemd:
      name: '{{ item }}'
      state: stopped
    loop:
       - 'mariadb-columnstore-cmapi'
       - 'mariadb-columnstore'
       - 'mariadb'

  - name: "Upgrading All Packages"
    package:
      name: '*'
      state: latest
      update_cache: yes

  - name: "Stopping Columnstore Processes"
    systemd:
      name: mariadb-columnstore
      state: stopped
      enabled: no

  - name: "Starting MariaDB Services"
    systemd:
      name: '{{ item }}'
      state: started
      enabled: yes
    loop:
       - 'mariadb-columnstore-cmapi'
       - 'mariadb'

  - name: "Wait For CMAPI To Start Up All Processes"
    wait_for:
      port: 8640
      delay: 20

- hosts: "mcs1"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Starting Up ColumnStore Cluster"
    uri:
      url: https://{{ hostvars.mcs1_private.ansible_host }}:8640/cmapi/0.4.0/cluster/start
      method: PUT
      headers:
        Content-Type: application/json
        x-api-key: "{{ api_key }}"
      validate_certs: no
      return_content: yes
      status_code: 200
      body_format: json
      body: '{"timeout":60}'
      timeout: 180

- hosts: "maxscale"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Clear Replicas From Maintenance Mode"
    uri:
      url: http://127.0.0.1:8989/v1/servers/{{ item }}/clear?state=maintenance
      method: PUT
      user: admin
      password: mariadb
      status_code: 204
    loop:
       - "mcs3"
       - "mcs2"
