---

columnstore_cnf: /etc/my.cnf.d/columnstore.cnf
git: git
htop: htop
jemalloc: jemalloc
jq: jq
mariadb_backup: MariaDB-backup
mariadb_cs_engine: MariaDB-columnstore-engine
mariadb_client: MariaDB-client
mariadb_libs: mariadb-libs
mariadb_repo: /etc/yum.repos.d/mariadb.repo
mariadb_server: MariaDB-server
mariadb_socket: /var/lib/mysql/mysql.sock
maxscale: maxscale
mlocate: mlocate
nano: nano
net_tools: net-tools
openssl: openssl
pre_task: dnf -y install epel-release && yum -y install glibc-locale-source glibc-langpack-en python2 python3 python2-PyMySQL python3-PyMySQL
server_cnf: /etc/my.cnf.d/server.cnf
wget: wget
